import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import SessionAuthProvider from "@/components/session-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionAuthProvider>
        {children}
        <Toaster 
          position="top-center"
          closeButton
          richColors
          expand={false}
          toastOptions={{
            style: {
              minWidth: '400px',
              maxWidth: '500px',
            },
            className: 'text-base'
          }}
        />
        </SessionAuthProvider>
      </body>
    </html>
  );
}
